services:
  fada-db:
    image: postgres:17.2-bullseye
    container_name: fada-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - fadapostgresvolume:/var/lib/postgresql/data
  
volumes:
  fadapostgresvolume: {}